language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

sudo: false

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/twig-bundle:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/form:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/validator:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/expression-language:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/twig-bridge:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/browser-kit:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/class-loader:${SYMFONY_VERSION} --no-update
  - php composer.phar update --prefer-stable --prefer-lowest

notifications:
  email:
    - payumsupport@forma-pro.com
